options:
  # Don't merge default rules
  # merge-default-rules: true
  formatter: stylish
  max-warnings: 50
rules:
  force-element-nesting: 0
  single-line-per-selector: 0
  extends-before-mixins: 2
  extends-before-declarations: 2
  empty-line-between-blocks: 0
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order: smacss
      ignore-custom-properties: true
variable-for-property:
  - 1
  -
    properties:
    - 'font-size'
    - 'color'
    - 'background-color'
    - 'font-family'
